targets:
  - name: aws-staging
    URL: 's3://vibe-beta.com?region=us-west-2'
    cloudFrontDistributionID: ENEIH6240I3TC
    exclude: 'lp/**'
  - name: aws-production
    URL: 's3://vibe.us?region=us-west-2'
    cloudFrontDistributionID: E1NS42WYS2Q8OI
    exclude: 'lp/**'
  - name: aws-cn-production
    URL: 's3://vibe.cn?region=cn-northwest-1'
    cloudFrontDistributionID: E1DLV4TUIX9CLK
    include: 'zh/**'

matchers:
  - pattern: "^.+\\.(js|css|svg|ttf|woff)$"
    cacheControl: 'max-age=31536000, no-transform, public'
    gzip: true
  - pattern: "^.+\\.(png|jpg|jpeg|gif|mp4)$"
    cacheControl: 'max-age=31536000, no-transform, public'
    gzip: false
  - pattern: "^.+\\.(html|xml|json)$"
    cacheControl: 'max-age=3600, no-transform, public'
    gzip: true
